### ISSUE TITLE
How to run CellHint in a sequential integration way

### ISSUE THREAD

**Issue by johnsCheng** [Teichlab/cellhint#8]
In my first run，CellHint integrated my cells well, with the major cell types (especially the epithelial cells) among samples (column `sample` as the batch) clustered together in UMAP. And the results motivate me to conduct further integration.
Then, I'd like to perform a second run to integrate my integrated cells and cells from a public dataset to remove potential batch (here, column `dataset` as the batch). I followed the instruction of Harmonisation and supervised integration.
However, I did remove the batch `dataset ` but not `sample`, the resulted UMAP seems retaining the batch `sample` in the first run, as the epithelial cells have many individual clusters. 
I'd like to remove the **both batches** from samples in my data and from different datasets, which data integration stratgey should I use with CellHint? 

thanks in advance

**Comment by ChuanXu1** [comment]
@johnsCheng, you can try to concatenate these two columns to form a new batch column for integration.

**Comment by johnsCheng** [comment]
my problem was solved, thanks for your kind advice! I'm getting the hang of it.
